#include "ChatEnums.hpp"

const char* ToString(ChatResultCode code) {
    switch (code) {
    case ChatResultCode::SUCCESS:
        return "SUCCESS";
    case ChatResultCode::TIMEOUT:
        return "TIMEOUT";
    case ChatResultCode::DUPLICATELOGIN:
        return "DUPLICATELOGIN";
    case ChatResultCode::SRCAVATARDOESNTEXIST:
        return "SRCAVATARDOESNTEXIST";
    case ChatResultCode::DESTAVATARDOESNTEXIST:
        return "DESTAVATARDOESNTEXIST";
    case ChatResultCode::ADDRESSDOESNTEXIST:
        return "ADDRESSDOESNTEXIST";
    case ChatResultCode::ADDRESSNOTROOM:
        return "ADDRESSNOTROOM";
    case ChatResultCode::ADDRESSNOTAID:
        return "ADDRESSNOTAID";
    case ChatResultCode::FRIENDNOTFOUND:
        return "FRIENDNOTFOUND";
    case ChatResultCode::ROOM_UNKNOWNFAILURE:
        return "ROOM_UNKNOWNFAILURE";
    case ChatResultCode::ROOM_SRCNOTINROOM:
        return "ROOM_SRCNOTINROOM";
    case ChatResultCode::ROOM_DESTNOTINROOM:
        return "ROOM_DESTNOTINROOM";
    case ChatResultCode::ROOM_BANNEDAVATAR:
        return "ROOM_BANNEDAVATAR";
    case ChatResultCode::ROOM_PRIVATEROOM:
        return "ROOM_PRIVATEROOM";
    case ChatResultCode::ROOM_MODERATEDROOM:
        return "ROOM_MODERATEDROOM";
    case ChatResultCode::ROOM_NOTINROOM:
        return "ROOM_NOTINROOM";
    case ChatResultCode::ROOM_NOPRIVILEGES:
        return "ROOM_NOPRIVILEGES";
    case ChatResultCode::DATABASE:
        return "DATABASE";
    case ChatResultCode::CANNOTGETAVATARID:
        return "CANNOTGETAVATARID";
    case ChatResultCode::CANNOTGETNODEID:
        return "CANNOTGETNODEID";
    case ChatResultCode::CANNOTGETPMSGID:
        return "CANNOTGETPMSGID";
    case ChatResultCode::PMSGNOTFOUND:
        return "PMSGNOTFOUND";
    case ChatResultCode::ROOMMAXAVATARSREACHED:
        return "ROOMMAXAVATARSREACHED";
    case ChatResultCode::IGNORING:
        return "IGNORING";
    case ChatResultCode::ROOM_ALREADYEXISTS:
        return "ROOM_ALREADYEXISTS";
    case ChatResultCode::NOTHINGTOCONFIRM:
        return "NOTHINGTOCONFIRM";
    case ChatResultCode::DUPLICATEFRIEND:
        return "DUPLICATEFRIEND";
    case ChatResultCode::IGNORENOTFOUND:
        return "IGNORENOTFOUND";
    case ChatResultCode::DUPLICATEIGNORE:
        return "DUPLICATEIGNORE";
    case ChatResultCode::DBFAIL:
        return "DBFAIL";
    case ChatResultCode::ROOM_DESTAVATARNOTMODERATOR:
        return "ROOM_DESTAVATARNOTMODERATOR";
    case ChatResultCode::ROOM_DESTAVATARNOTINVITED:
        return "ROOM_DESTAVATARNOTINVITED";
    case ChatResultCode::ROOM_DESTAVATARNOTBANNED:
        return "ROOM_DESTAVATARNOTBANNED";
    case ChatResultCode::ROOM_DUPLICATEBAN:
        return "ROOM_DUPLICATEBAN";
    case ChatResultCode::ROOM_DUPLICATEMODERATOR:
        return "ROOM_DUPLICATEMODERATOR";
    case ChatResultCode::ROOM_DUPLICATEINVITE:
        return "ROOM_DUPLICATEINVITE";
    case ChatResultCode::ROOM_ALREADYINROOM:
        return "ROOM_ALREADYINROOM";
    case ChatResultCode::ROOM_PARENTNONPERSISTENT:
        return "ROOM_PARENTNONPERSISTENT";
    case ChatResultCode::ROOM_PARENTBADNODETYPE:
        return "ROOM_PARENTBADNODETYPE";
    case ChatResultCode::NOFANCLUBHANDLE:
        return "NOFANCLUBHANDLE";
    case ChatResultCode::AIDALREADYEXISTS:
        return "AIDALREADYEXISTS";
    case ChatResultCode::UIDALREADYEXISTS:
        return "UIDALREADYEXISTS";
    case ChatResultCode::WRONGCHATSERVERFORREQUEST:
        return "WRONGCHATSERVERFORREQUEST";
    case ChatResultCode::SUCCESSBADDATA:
        return "SUCCESSBADDATA";
    case ChatResultCode::NULLNAMELOGIN:
        return "NULLNAMELOGIN";
    case ChatResultCode::SERVER_IDENTITY_EMPTY:
        return "SERVER_IDENTITY_EMPTY";
    case ChatResultCode::SERVER_IDENTITY_TAKEN:
        return "SERVER_IDENTITY_TAKEN";
    case ChatResultCode::REMOTESERVERDOWN:
        return "REMOTESERVERDOWN";
    case ChatResultCode::NODEIDCONFLICT:
        return "NODEIDCONFLICT";
    case ChatResultCode::INVALIDNODENAME:
        return "INVALIDNODENAME";
    case ChatResultCode::INSUFFICIENTGMPRIVS:
        return "INSUFFICIENTGMPRIVS";
    case ChatResultCode::SNOOPALREADYADDED:
        return "SNOOPALREADYADDED";
    case ChatResultCode::NOTSNOOPING:
        return "NOTSNOOPING";
    case ChatResultCode::ROOM_DESTAVATARNOTTEMPORARYMODERATOR:
        return "ROOM_DESTAVATARNOTTEMPORARYMODERATOR";
    case ChatResultCode::ROOM_DESTAVATARNOTVOICE:
        return "ROOM_DESTAVATARNOTVOICE";
    case ChatResultCode::ROOM_DUPLICATETEMPORARYMODERATOR:
        return "ROOM_DUPLICATETEMPORARYMODERATOR";
    case ChatResultCode::ROOM_DUPLICATEVOICE:
        return "ROOM_DUPLICATEVOICE";
    case ChatResultCode::AVATARMUSTBELOGGEDOUT:
        return "AVATARMUSTBELOGGEDOUT";
    case ChatResultCode::NOTHINGTODO:
        return "NOTHINGTODO";
    case ChatResultCode::TRANSFERNAMENULL:
        return "TRANSFERNAMENULL";
    case ChatResultCode::TRANSFERUSERIDZERO:
        return "TRANSFERUSERIDZERO";
    case ChatResultCode::TRANSFERADDRESSNULL:
        return "TRANSFERADDRESSNULL";
    case ChatResultCode::OUTOFIDS:
        return "OUTOFIDS";
    case ChatResultCode::ROOM_LOCALROOM:
        return "ROOM_LOCALROOM";
    case ChatResultCode::ROOM_GAMEROOM:
        return "ROOM_GAMEROOM";
    case ChatResultCode::ROOM_DESTAVATARNOTENTERING:
        return "ROOM_DESTAVATARNOTENTERING";
    case ChatResultCode::INSUFFICIENTPRIORITY:
        return "INSUFFICIENTPRIORITY";
    case ChatResultCode::ROOM_WAITINGFORENTRY:
        return "ROOM_WAITINGFORENTRY";
    case ChatResultCode::INBOXLIMITEXCEEDED:
        return "INBOXLIMITEXCEEDED";
    case ChatResultCode::DUPLICATEDESTINATION:
        return "DUPLICATEDESTINATION";
    case ChatResultCode::CATEGORYLIMITEXCEEDED:
        return "CATEGORYLIMITEXCEEDED";
    case ChatResultCode::MESSAGE_FILTER_FAILURE:
        return "MESSAGE_FILTER_FAILURE";
    case ChatResultCode::INVALID_INPUT:
        return "INVALID_INPUT";
    };

    return "";
}
