
#pragma once

#include <cstdint>
#include <string>

enum class ChatRequestType : uint16_t {
    LOGINAVATAR = 0,
    LOGOUTAVATAR,
    DESTROYAVATAR,
    GETAVATAR,
    CREATEROOM,
    DESTROYROOM, // 5
    SENDINSTANTMESSAGE,
    SENDROOMMESSAGE,
    SENDBROADCASTMESSAGE,
    ADDFRIEND,
    REMOVEFRIEND, // 10
    FRIENDSTATUS,
    ADDIGNORE,
    REMOVEIGNORE,
    ENTERROOM,
    LEAVEROOM, // 15
    ADDMODERATOR,
    REMOVEMODERATOR,
    ADDBAN,
    REMOVEBAN,
    ADDINVITE, // 20
    REMOVEINVITE,
    KICKAVATAR,
    SETROOMPARAMS,
    GETROOM,
    GETROOMSUMMARIES, // 25
    SENDPERSISTENTMESSAGE,
    GETPERSISTENTHEADERS,
    GETPERSISTENTMESSAGE,
    UPDATEPERSISTENTMESSAGE,
    UNREGISTERROOM, // 30
    IGNORESTATUS,
    FAILOVER_RELOGINAVATAR,
    FAILOVER_RECREATEROOM,
    CONFIRMFRIEND,
    GETAVATARKEYWORDS, // 35
    SETAVATARKEYWORDS,
    SEARCHAVATARKEYWORDS,
    GETFANCLUBHANDLE,
    UPDATEPERSISTENTMESSAGES,
    FINDAVATARBYUID, // 40
    CHANGEROOMOWNER,
    SETAPIVERSION,
    ADDTEMPORARYMODERATOR,
    REMOVETEMPORARYMODERATOR,
    GRANTVOICE, // 45
    REVOKEVOICE,
    SETAVATARATTRIBUTES,
    ADDSNOOPAVATAR,
    REMOVESNOOPAVATAR,
    ADDSNOOPROOM, // 50
    REMOVESNOOPROOM,
    GETSNOOPLIST,
    PARTIALPERSISTENTHEADERS,
    COUNTPERSISTENTMESSAGES,
    PURGEPERSISTENTMESSAGES, // 55
    SETFRIENDCOMMENT,
    TRANSFERAVATAR,
    CHANGEPERSISTENTFOLDER,
    ALLOWROOMENTRY,
    SETAVATAREMAIL, // 60
    SETAVATARINBOXLIMIT,
    SENDMULTIPLEPERSISTENTMESSAGES,
    GETMULTIPLEPERSISTENTMESSAGES,
    ALTERPERISTENTMESSAGE,
    GETANYAVATAR, // 65
    TEMPORARYAVATAR,
    AVATARLIST,
    SETAVATARSTATUSMESSAGE,
    CONFIRMFRIEND_RECIPROCATE,
    ADDFRIEND_RECIPROCATE, // 70
    REMOVEFRIEND_RECIPROCATE,
    FILTERMESSAGE,
    FILTERMESSAGE_EX,
    REGISTRAR_GETCHATSERVER = 20001,
};

enum class ChatResponseType : uint16_t {
    LOGINAVATAR = 0,
    LOGOUTAVATAR,
    DESTROYAVATAR,
    GETAVATAR,
    CREATEROOM,
    DESTROYROOM,
    SENDINSTANTMESSAGE,
    SENDROOMMESSAGE,
    SENDBROADCASTMESSAGE,
    ADDFRIEND,
    REMOVEFRIEND,
    FRIENDSTATUS,
    ADDIGNORE,
    REMOVEIGNORE,
    ENTERROOM,
    LEAVEROOM,
    ADDMODERATOR,
    REMOVEMODERATOR,
    ADDBAN,
    REMOVEBAN,
    ADDINVITE,
    REMOVEINVITE,
    KICKAVATAR,
    SETROOMPARAMS,
    GETROOM,
    GETROOMSUMMARIES,
    SENDPERSISTENTMESSAGE,
    GETPERSISTENTHEADERS,
    GETPERSISTENTMESSAGE,
    UPDATEPERSISTENTMESSAGE,
    UNREGISTERROOM,
    IGNORESTATUS,
    FAILOVER_RELOGINAVATAR,
    FAILOVER_RECREATEROOM,
    CONFIRMFRIEND,
    GETAVATARKEYWORDS,
    SETAVATARKEYWORDS,
    SEARCHAVATARKEYWORDS,
    GETFANCLUBHANDLE,
    UPDATEPERSISTENTMESSAGES,
    FINDAVATARBYUID,
    CHANGEROOMOWNER,
    SETAPIVERSION,
    ADDTEMPORARYMODERATOR,
    REMOVETEMPORARYMODERATOR,
    GRANTVOICE,
    REVOKEVOICE,
    SETAVATARATTRIBUTES,
    ADDSNOOPAVATAR,
    REMOVESNOOPAVATAR,
    ADDSNOOPROOM,
    REMOVESNOOPROOM,
    GETSNOOPLIST,
    PARTIALPERSISTENTHEADERS,
    COUNTPERSISTENTMESSAGES,
    PURGEPERSISTENTMESSAGES,
    SETFRIENDCOMMENT,
    TRANSFERAVATAR,
    CHANGEPERSISTENTFOLDER,
    ALLOWROOMENTRY,
    SETAVATAREMAIL,
    SETAVATARINBOXLIMIT,
    SENDMULTIPLEPERSISTENTMESSAGES,
    GETMULTIPLEPERSISTENTMESSAGES,
    ALTERPERSISTENTMESSAGE,
    GETANYAVATAR,
    TEMPORARYAVATAR,
    AVATARLIST,
    SETSTATUSMESSAGE,
    CONFIRMFRIEND_RECIPROCATE,
    ADDFRIEND_RECIPROCATE,
    REMOVEFRIEND_RECIPROCATE,
    FILTERMESSAGE,
    FILTERMESSAGE_EX,

    REGISTRAR_GETCHATSERVER = 20001,
};

enum class ChatResultCode : uint32_t {
    SUCCESS = 0,
    TIMEOUT = 1,
    DUPLICATELOGIN,
    SRCAVATARDOESNTEXIST,
    DESTAVATARDOESNTEXIST,
    ADDRESSDOESNTEXIST, // 5
    ADDRESSNOTROOM,
    ADDRESSNOTAID,
    FRIENDNOTFOUND,
    ROOM_UNKNOWNFAILURE,
    ROOM_SRCNOTINROOM, // 10
    ROOM_DESTNOTINROOM,
    ROOM_BANNEDAVATAR,
    ROOM_PRIVATEROOM,
    ROOM_MODERATEDROOM,
    ROOM_NOTINROOM, // 15
    ROOM_NOPRIVILEGES,
    DATABASE,
    CANNOTGETAVATARID,
    CANNOTGETNODEID,
    CANNOTGETPMSGID, // 20
    PMSGNOTFOUND,
    ROOMMAXAVATARSREACHED,
    IGNORING,
    ROOM_ALREADYEXISTS,
    NOTHINGTOCONFIRM, // 25
    DUPLICATEFRIEND,
    IGNORENOTFOUND,
    DUPLICATEIGNORE,
    DBFAIL,
    ROOM_DESTAVATARNOTMODERATOR, // 30
    ROOM_DESTAVATARNOTINVITED,
    ROOM_DESTAVATARNOTBANNED,
    ROOM_DUPLICATEBAN,
    ROOM_DUPLICATEMODERATOR,
    ROOM_DUPLICATEINVITE, // 35
    ROOM_ALREADYINROOM,
    ROOM_PARENTNONPERSISTENT,
    ROOM_PARENTBADNODETYPE,
    NOFANCLUBHANDLE,
    AIDALREADYEXISTS, // 40
    UIDALREADYEXISTS,
    WRONGCHATSERVERFORREQUEST,
    SUCCESSBADDATA,
    NULLNAMELOGIN,
    SERVER_IDENTITY_EMPTY, // 45
    SERVER_IDENTITY_TAKEN,
    REMOTESERVERDOWN,
    NODEIDCONFLICT,
    INVALIDNODENAME,
    INSUFFICIENTGMPRIVS, // 50
    SNOOPALREADYADDED,
    NOTSNOOPING,
    ROOM_DESTAVATARNOTTEMPORARYMODERATOR,
    ROOM_DESTAVATARNOTVOICE,
    ROOM_DUPLICATETEMPORARYMODERATOR, // 55
    ROOM_DUPLICATEVOICE,
    AVATARMUSTBELOGGEDOUT,
    NOTHINGTODO,
    TRANSFERNAMENULL,
    TRANSFERUSERIDZERO, // 60
    TRANSFERADDRESSNULL,
    OUTOFIDS,
    ROOM_LOCALROOM,
    ROOM_GAMEROOM,
    ROOM_DESTAVATARNOTENTERING, // 65
    INSUFFICIENTPRIORITY,
    ROOM_WAITINGFORENTRY,
    INBOXLIMITEXCEEDED,
    DUPLICATEDESTINATION,
    CATEGORYLIMITEXCEEDED, // 70
    MESSAGE_FILTER_FAILURE,
    INVALID_INPUT,
};

struct ChatResultException {
    ChatResultCode code;
    std::string message;

    explicit ChatResultException(const ChatResultCode result)
        : code{result} {}

    ChatResultException(const ChatResultCode result, char const * text)
        : code{result}
        , message{text} {}
};

const char* ToString(ChatResultCode code);